# Generated by Django 4.1 on 2025-10-29 11:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialBalance',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ledger.account', verbose_name='勘定科目')),
                ('balance', models.IntegerField(default=0, verbose_name='残高')),
                ('start_date', models.DateField(default=datetime.date(2025, 4, 1), verbose_name='会計期間開始日')),
            ],
            options={
                'verbose_name': '期首残高',
                'verbose_name_plural': '期首残高',
            },
        ),
    ]
