# Generated by Django 4.1 on 2025-11-10 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0003_alter_initialbalance_options_salesdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedetail',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='description',
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='journal_entry_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_journal_entries', to='ledger.journalentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14, verbose_name='単価'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='journal_entry_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_journal_entries', to='ledger.journalentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14, verbose_name='単価'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='ledger.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_items', to='ledger.item'),
            preserve_default=False,
        ),
    ]
