# Generated by Django 4.1 on 2025-11-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_remove_purchasedetail_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='company_id',
            new_name='company',
        ),
    ]
