# Generated by Django 4.1 on 2025-11-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_rename_company_id_journalentry_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='journal_entry_id',
            new_name='journal_entry',
        ),
        migrations.RenameField(
            model_name='salesdetail',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='salesdetail',
            old_name='journal_entry_id',
            new_name='journal_entry',
        ),
    ]
