# Generated by Django 4.1 on 2025-11-15 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_rename_item_id_purchasedetail_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedetail',
            options={'verbose_name': 'Purchase Detail', 'verbose_name_plural': 'purchase_details'},
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_details', to='ledger.item'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_details', to='ledger.journalentry'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_details', to='ledger.item'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_details', to='ledger.journalentry'),
        ),
    ]
