# Generated by Django 4.1 on 2026-01-19 11:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0007_alter_purchasedetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_adjustment_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('normal', '通常仕訳'), ('adjustment', '決算整理仕訳'), ('closing', '決算振替仕訳')], default='normal', max_length=32, verbose_name='仕訳タイプ'),
        ),
        migrations.AlterField(
            model_name='initialbalance',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 4, 1), verbose_name='会計期間開始日'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(verbose_name='取引日'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='summary',
            field=models.TextField(blank=True, verbose_name='摘要'),
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='会計期間名')),
                ('start_date', models.DateField(verbose_name='会計期間開始日')),
                ('end_date', models.DateField(verbose_name='会計期間終了日')),
                ('is_closed', models.BooleanField(default=False, verbose_name='締め済みフラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscalperiods_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscalperiods_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiscal Period',
                'verbose_name_plural': 'Fiscal Periods',
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='ledger.fiscalperiod', verbose_name='会計期間'),
        ),
    ]
