# Generated by Django 4.1 on 2026-01-19 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0008_account_is_adjustment_only_journalentry_entry_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='資産名')),
                ('asset_number', models.CharField(max_length=50, unique=True, verbose_name='資産番号')),
                ('acquisition_date', models.DateField(verbose_name='取得日')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='取得価額')),
                ('depreciation_method', models.CharField(choices=[('straight_line', '定額法'), ('declining_balance', '定率法')], default='straight_line', max_length=20, verbose_name='償却方法')),
                ('useful_life', models.IntegerField(verbose_name='耐用年数')),
                ('residual_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='残存価額')),
                ('status', models.CharField(choices=[('active', '使用中'), ('disposed', '除却済'), ('sold', '売却済')], default='active', max_length=20, verbose_name='ステータス')),
                ('disposal_date', models.DateField(blank=True, null=True, verbose_name='除却/売却日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('account', models.ForeignKey(limit_choices_to={'type': 'asset'}, on_delete=django.db.models.deletion.PROTECT, to='ledger.account', verbose_name='勘定科目')),
                ('acquisition_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acquired_assets', to='ledger.journalentry', verbose_name='取得仕訳')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.company', verbose_name='会社')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixedassets_created', to=settings.AUTH_USER_MODEL)),
                ('disposal_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposed_assets', to='ledger.journalentry', verbose_name='除却/売却仕訳')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixedassets_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '固定資産',
                'verbose_name_plural': '固定資産台帳',
                'ordering': ['asset_number'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='償却額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciationhistories_created', to=settings.AUTH_USER_MODEL)),
                ('depreciation_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_record', to='ledger.journalentry', verbose_name='減価償却仕訳')),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.fiscalperiod', verbose_name='会計期間')),
                ('fixed_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_history', to='ledger.fixedasset', verbose_name='固定資産')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciationhistories_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '減価償却履歴',
                'verbose_name_plural': '減価償却履歴',
                'ordering': ['-fiscal_period__end_date'],
                'unique_together': {('fixed_asset', 'fiscal_period')},
            },
        ),
    ]
