# Generated by Django 4.1 on 2026-01-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_fixedasset_depreciationhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedasset',
            name='company',
        ),
    ]
