# Generated by Django 4.1 on 2026-02-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_remove_fixedasset_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciationhistory',
            name='depreciation_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_records', to='ledger.journalentry', verbose_name='減価償却仕訳'),
        ),
    ]
